### ISSUE TITLE
pod error

### ISSUE THREAD

**Issue by GeekYW** [MichaelHuyp/Bilibili_Wuxianda#1]
当我pod的时候出现这个问题

[!] Error installing Realm
[!] /Applications/Xcode.app/Contents/Developer/usr/bin/git clone git@github.com:realm/realm-cocoa.git /var/folders/lk/wdhcms2s6j16vnmnqhrr6q80fbjp1k/T/d20160728-64202-u6bg1m --single-branch --depth 1

Cloning into '/var/folders/lk/wdhcms2s6j16vnmnqhrr6q80fbjp1k/T/d20160728-64202-u6bg1m'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by MichaelHuyp** [comment]
将podfile文件git@github.com:realm/realm-cocoa.git那一句改成https://github.com/realm/realm-cocoa.git 试试

**Comment by GeekYW** [comment]
pod 卡在这

Analyzing dependencies
Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`

**Comment by MichaelHuyp** [comment]
@GeekYW  等下吧 Realm包很大

**Comment by GeekYW** [comment]
恩恩，谢谢大神
