### ISSUE TITLE
你好作者，pod之后找不到<IJKMediaFramework/IJKMediaFramework.h>

### ISSUE THREAD

**Issue by wanghanfeng** [MichaelHuyp/Bilibili_Wuxianda#17]
pod 之后 一直报错 #import <IJKMediaFramework/IJKMediaFramework.h>，找不到头文件

**Comment by wanghanfeng** [comment]
好像是IJKMediaPlayFramework在github上找不到了。。。。。

**Comment by feng-tianyou** [comment]
这个是ijkplayer集成的，你在简书搜一下，有的已经集成好的。

**Comment by pinguo-mazhong** [comment]
新clone下来的工程里已经包含了一个IJKMediaFramework.framework，但是引用有问题。在project navigator里删除对IJKMediaFramework.framework的引用，然后重新把IJKMediaFramework.framework拖进来就可以了。（不用重新去百度盘里下IJKMediaFramework.framework）

**Comment by MichaelHuyp** [comment]
@wanghanfeng  以下是我打包的ijkplayer Framework 下载之后拖进项目，项目即可成功运行 链接: http://pan.baidu.com/s/1gfmE5u7 密码: 6jta
