### ISSUE TITLE
Pod Error Realm

### ISSUE THREAD

**Issue by ajaybeniwal** [MichaelHuyp/Bilibili_Wuxianda#4]
Analyzing dependencies
Pre-downloading: `Realm` from `https://github.com/realm/realm-cocoa.git`
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: core 1.4.1

ERROR: One of Realm's submodules is missing!

If you're using Realm and/or RealmSwift from a git branch, please add 'submodules: true' to
their entries in your Podfile.

**Comment by MichaelHuyp** [comment]
@ajaybeniwal Re-download the code,Try again 'pod install'

**Comment by danielgalasko** [comment]
Odd, I have tried several times and it still keeps failing with the same error

**Comment by MichaelHuyp** [comment]
@danielgalasko Ensure that the code is up to date。 I just tried it, no problem

**Comment by raphaels17** [comment]
same error
