### ISSUE TITLE
你好作者大神,GPUImageContext.h file not found

### ISSUE THREAD

**Issue by harofan** [MichaelHuyp/Bilibili_Wuxianda#6]
我把pod install,也把ijkplayer导入了,那刚开始的5个错解决了,podfile里GPUImage框架被注释掉了,我把注释取消掉然后从新安装发现还是少一个文件啊GPUImageContext.h file not found,求指教啊

**Comment by MichaelHuyp** [comment]
@SkyHarute  注释不要取消掉。。 因为来疯直播框架的LFLiveKit 已经包含了GPUImage 因此就没有必要导入GPUImage官方的podfile了， 出现这个原因可能是你的Pods版本为1.0  我用0.39.0版本的Pods是没问题的  我在README里面又说这个问题

**Comment by harofan** [comment]
@MichaelHuyp 是这样的,我看过你的readme和简书了,以及下面的评论的,我已经把pod退回到0.39.0版本的,如果注释不取消运行就会发现有五个编译错误的,基本都是找不到0.0.你的简书里有两位朋友也遇到了同样的情况

**Comment by MichaelHuyp** [comment]
@SkyHarute 具体是哪几个编译错误。。

**Comment by harofan** [comment]
@MichaelHuyp 这是注释去掉前下拉的,目前是这两个错误
![2016-08-01 3 45 21](https://cloud.githubusercontent.com/assets/20294470/17286887/fe606c32-57fe-11e6-8c8d-ccd1cb30609c.png)

GPUImage/GLProgram.h
GPUImageFilter.h
这两个文件找不到

**Comment by MichaelHuyp** [comment]
@SkyHarute clean一下项目。。 再pod update一下试试  我这边0.39.0的Pods没问题的啊。。 看下https://github.com/CocoaPods/CocoaPods/issues/4605这个issues  尝试将Pods的Always Search User Path 设置为YES 试试

**Comment by harofan** [comment]
@MichaelHuyp 恩,已经可以了,pod update到最新后发现依然报错,此时把Pods的Always Search User Path 设置为YES,再次编译提示缺少ijkplayer,将你的包导入就好啦,谢啦学习了,我就是特别想去B站才来学IOS的哈哈

**Comment by JustToBeBetter** [comment]
cocoa pods 1.0跑不动？只能用0.39.0？
![Uploading 屏幕快照 2016-08-01 下午6.01.18.png…]()

**Comment by MichaelHuyp** [comment]
@JustToBeBetter 好像是这样的。

**Comment by harofan** [comment]
cocoa pods 1.0这个实测可以跑得动, @MichaelHuyp 大神你的B站素材包哪来的啊?接口就是用charles慢慢抓吗?现在开始想仿写B站客户端了0.0

**Comment by MichaelHuyp** [comment]
@SkyHarute  恩 都是利用业余时间断断续续写的，写的比较粗糙。 B站前段时间更改了签名验证方式。。 所以很多接口没办法用了 只能用假数据

**Comment by SinAlfa** [comment]
pod下来之以后   resultType.swift 报错啊  84个。。。

**Comment by harofan** [comment]
@SinAlfa 升级XCODE到7.3 swift版本语法的问题,虽然我很讨厌7.3

**Comment by harofan** [comment]
@MichaelHuyp 你有没有遇到过写着写着一直都正常的,突然加了一两句代码就提示link不到,感觉就像是第三方框架没有支持模拟器架构那种问题一样,这个时候我把代码删了也没用的,只能在真机运行了,以前还好好的...

**Comment by cooliean** [comment]
弄死都还是  GPUImage/GLProgram.h
GPUImageFilter.h
这两个文件找不到
我的cocopod版本是1.0.1

**Comment by harofan** [comment]
引入第三方框架其实最好还是改变一下命名
